### YamlMime:ManagedReference
items:
- uid: SadConsole.Game.ConfigurationFontLoader
  commentId: T:SadConsole.Game.ConfigurationFontLoader
  id: Game.ConfigurationFontLoader
  parent: SadConsole
  children:
  - SadConsole.Game.ConfigurationFontLoader.#ctor
  - SadConsole.Game.ConfigurationFontLoader.AddExtraFonts(System.String[])
  - SadConsole.Game.ConfigurationFontLoader.UseBuiltinFont
  - SadConsole.Game.ConfigurationFontLoader.UseBuiltinFontExtended
  - SadConsole.Game.ConfigurationFontLoader.UseCustomFont(System.String)
  langs:
  - csharp
  - vb
  name: Game.ConfigurationFontLoader
  nameWithType: Game.ConfigurationFontLoader
  fullName: SadConsole.Game.ConfigurationFontLoader
  type: Class
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole
  summary: Settings for loading fonts at the start of a game.
  example: []
  syntax:
    content: public class Game.ConfigurationFontLoader
    content.vb: Public Class Game.ConfigurationFontLoader
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: SadConsole.Game.ConfigurationFontLoader.UseBuiltinFont
  commentId: M:SadConsole.Game.ConfigurationFontLoader.UseBuiltinFont
  id: UseBuiltinFont
  parent: SadConsole.Game.ConfigurationFontLoader
  langs:
  - csharp
  - vb
  name: UseBuiltinFont()
  nameWithType: Game.ConfigurationFontLoader.UseBuiltinFont()
  fullName: SadConsole.Game.ConfigurationFontLoader.UseBuiltinFont()
  type: Method
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole
  summary: Sets the default font to the SadConsole standard font, an IBM 8x16 font.
  example: []
  syntax:
    content: public void UseBuiltinFont()
    content.vb: Public Sub UseBuiltinFont()
  overload: SadConsole.Game.ConfigurationFontLoader.UseBuiltinFont*
- uid: SadConsole.Game.ConfigurationFontLoader.UseBuiltinFontExtended
  commentId: M:SadConsole.Game.ConfigurationFontLoader.UseBuiltinFontExtended
  id: UseBuiltinFontExtended
  parent: SadConsole.Game.ConfigurationFontLoader
  langs:
  - csharp
  - vb
  name: UseBuiltinFontExtended()
  nameWithType: Game.ConfigurationFontLoader.UseBuiltinFontExtended()
  fullName: SadConsole.Game.ConfigurationFontLoader.UseBuiltinFontExtended()
  type: Method
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole
  summary: Sets the default font to the SadConsole extended font, an IBM 8x16 font with SadConsole specific characters past index 255.
  example: []
  syntax:
    content: public void UseBuiltinFontExtended()
    content.vb: Public Sub UseBuiltinFontExtended()
  overload: SadConsole.Game.ConfigurationFontLoader.UseBuiltinFontExtended*
- uid: SadConsole.Game.ConfigurationFontLoader.UseCustomFont(System.String)
  commentId: M:SadConsole.Game.ConfigurationFontLoader.UseCustomFont(System.String)
  id: UseCustomFont(System.String)
  parent: SadConsole.Game.ConfigurationFontLoader
  langs:
  - csharp
  - vb
  name: UseCustomFont(string)
  nameWithType: Game.ConfigurationFontLoader.UseCustomFont(string)
  fullName: SadConsole.Game.ConfigurationFontLoader.UseCustomFont(string)
  type: Method
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole
  summary: Sets the default font in SadConsole to the specified font file.
  example: []
  syntax:
    content: public void UseCustomFont(string fontFile)
    parameters:
    - id: fontFile
      type: System.String
      description: ''
    content.vb: Public Sub UseCustomFont(fontFile As String)
  overload: SadConsole.Game.ConfigurationFontLoader.UseCustomFont*
  nameWithType.vb: Game.ConfigurationFontLoader.UseCustomFont(String)
  fullName.vb: SadConsole.Game.ConfigurationFontLoader.UseCustomFont(String)
  name.vb: UseCustomFont(String)
- uid: SadConsole.Game.ConfigurationFontLoader.AddExtraFonts(System.String[])
  commentId: M:SadConsole.Game.ConfigurationFontLoader.AddExtraFonts(System.String[])
  id: AddExtraFonts(System.String[])
  parent: SadConsole.Game.ConfigurationFontLoader
  langs:
  - csharp
  - vb
  name: AddExtraFonts(params string[])
  nameWithType: Game.ConfigurationFontLoader.AddExtraFonts(params string[])
  fullName: SadConsole.Game.ConfigurationFontLoader.AddExtraFonts(params string[])
  type: Method
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole
  summary: Loads the provided font files into SadConsole.
  example: []
  syntax:
    content: public void AddExtraFonts(params string[] fontFiles)
    parameters:
    - id: fontFiles
      type: System.String[]
      description: An array of font files to load.
    content.vb: Public Sub AddExtraFonts(ParamArray fontFiles As String())
  overload: SadConsole.Game.ConfigurationFontLoader.AddExtraFonts*
  nameWithType.vb: Game.ConfigurationFontLoader.AddExtraFonts(ParamArray String())
  fullName.vb: SadConsole.Game.ConfigurationFontLoader.AddExtraFonts(ParamArray String())
  name.vb: AddExtraFonts(ParamArray String())
- uid: SadConsole.Game.ConfigurationFontLoader.#ctor
  commentId: M:SadConsole.Game.ConfigurationFontLoader.#ctor
  id: '#ctor'
  parent: SadConsole.Game.ConfigurationFontLoader
  langs:
  - csharp
  - vb
  name: ConfigurationFontLoader()
  nameWithType: Game.ConfigurationFontLoader.ConfigurationFontLoader()
  fullName: SadConsole.Game.ConfigurationFontLoader.ConfigurationFontLoader()
  type: Constructor
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole
  syntax:
    content: public ConfigurationFontLoader()
    content.vb: Public Sub New()
  overload: SadConsole.Game.ConfigurationFontLoader.#ctor*
  nameWithType.vb: Game.ConfigurationFontLoader.New()
  fullName.vb: SadConsole.Game.ConfigurationFontLoader.New()
  name.vb: New()
references:
- uid: SadConsole
  commentId: N:SadConsole
  isExternal: true
  href: SadConsole.html
  name: SadConsole
  nameWithType: SadConsole
  fullName: SadConsole
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SadConsole.Game.ConfigurationFontLoader.UseBuiltinFont*
  commentId: Overload:SadConsole.Game.ConfigurationFontLoader.UseBuiltinFont
  isExternal: true
  href: SadConsole.Game.ConfigurationFontLoader.html#SadConsole.Game.ConfigurationFontLoader.UseBuiltinFont
  name: UseBuiltinFont
  nameWithType: Game.ConfigurationFontLoader.UseBuiltinFont
  fullName: SadConsole.Game.ConfigurationFontLoader.UseBuiltinFont
- uid: SadConsole.Game.ConfigurationFontLoader.UseBuiltinFontExtended*
  commentId: Overload:SadConsole.Game.ConfigurationFontLoader.UseBuiltinFontExtended
  isExternal: true
  href: SadConsole.Game.ConfigurationFontLoader.html#SadConsole.Game.ConfigurationFontLoader.UseBuiltinFontExtended
  name: UseBuiltinFontExtended
  nameWithType: Game.ConfigurationFontLoader.UseBuiltinFontExtended
  fullName: SadConsole.Game.ConfigurationFontLoader.UseBuiltinFontExtended
- uid: SadConsole.Game.ConfigurationFontLoader.UseCustomFont*
  commentId: Overload:SadConsole.Game.ConfigurationFontLoader.UseCustomFont
  isExternal: true
  href: SadConsole.Game.ConfigurationFontLoader.html#SadConsole.Game.ConfigurationFontLoader.UseCustomFont(System.String)
  name: UseCustomFont
  nameWithType: Game.ConfigurationFontLoader.UseCustomFont
  fullName: SadConsole.Game.ConfigurationFontLoader.UseCustomFont
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: SadConsole.Game.ConfigurationFontLoader.AddExtraFonts*
  commentId: Overload:SadConsole.Game.ConfigurationFontLoader.AddExtraFonts
  isExternal: true
  href: SadConsole.Game.ConfigurationFontLoader.html#SadConsole.Game.ConfigurationFontLoader.AddExtraFonts(System.String[])
  name: AddExtraFonts
  nameWithType: Game.ConfigurationFontLoader.AddExtraFonts
  fullName: SadConsole.Game.ConfigurationFontLoader.AddExtraFonts
- uid: System.String[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string[]
  nameWithType: string[]
  fullName: string[]
  nameWithType.vb: String()
  fullName.vb: String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: (
  - name: )
- uid: SadConsole.Game.ConfigurationFontLoader.#ctor*
  commentId: Overload:SadConsole.Game.ConfigurationFontLoader.#ctor
  isExternal: true
  href: SadConsole.Game.ConfigurationFontLoader.html#SadConsole.Game.ConfigurationFontLoader.#ctor
  name: ConfigurationFontLoader
  nameWithType: Game.ConfigurationFontLoader.ConfigurationFontLoader
  fullName: SadConsole.Game.ConfigurationFontLoader.ConfigurationFontLoader
  nameWithType.vb: Game.ConfigurationFontLoader.New
  fullName.vb: SadConsole.Game.ConfigurationFontLoader.New
  name.vb: New
