slogan: "Oldschool all the way."

menu:
  - title: Blog
    url: blog
    intro: "All the articles"
    # icon: "fa fa-archive"
  - title: Documentation
    url: docs
    intro: "Documentation for SadConsole"
    # icon: "fa fa-folder"
  #- title: Tags
  #  url: tags
  #  intro: "All the tags."
    # icon: "fa fa-tags"
  #- title: About
  #  url: about
  #  intro: "About me"
    # icon: "fa fa-user"
  - title: Github
    url: https://github.com/thraka/sadconsole
    intro: "SadConsole GitHub"
    icon: "fa fa-github"
  - title: Reddit
    url: https://www.reddit.com/r/sadconsole/
    intro: "SadConsole SubReddit"
    icon: "fa fa-reddit"
  - title: RSS
    url: atom.xml
    intro: "Subscribe"
    icon: "fa fa-rss"

    
    
    
links:
  - title: SadConsole
    url: https://github.com/thraka/sadconsole
    intro: "SadConsole Github."
    icon: "fa fa-github"
  - title: Reddit
    url: https://www.reddit.com/r/sadconsole/
    intro: "SadConsole SubReddit"
    icon: "fa fa-reddit"
  # - title: "My LinkedIn"
  #   url: http://www.linkedin.com/in/xxx
  #   intro: "My Linkin account."
  #   icon: "fa fa-linkedin"

widgets:
#- search
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname:
disqus_shortname: sadconsoleblog


# Analytics (change to yours)
google_analytics:
  enable: true
  siteid: UA-76753055-1
baidu_tongji:
  enable: false
  siteid: 

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
