### YamlMime:ManagedReference
items:
- uid: SadConsole.Configuration.IConfigurator
  commentId: T:SadConsole.Configuration.IConfigurator
  id: IConfigurator
  parent: SadConsole.Configuration
  children:
  - SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.BuilderBase,SadConsole.GameHost)
  langs:
  - csharp
  - vb
  name: IConfigurator
  nameWithType: IConfigurator
  fullName: SadConsole.Configuration.IConfigurator
  type: Interface
  assemblies:
  - SadConsole
  namespace: SadConsole.Configuration
  summary: Configuration interface that's added to the <xref href="SadConsole.Configuration.Builder" data-throw-if-not-resolved="false"></xref> object.
  example: []
  syntax:
    content: public interface IConfigurator
    content.vb: Public Interface IConfigurator
  extensionMethods:
  - System.Object.SadConsole.ExtensionsSystem.GetDebuggerDisplayValue
- uid: SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.BuilderBase,SadConsole.GameHost)
  commentId: M:SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.BuilderBase,SadConsole.GameHost)
  id: Run(SadConsole.Configuration.BuilderBase,SadConsole.GameHost)
  parent: SadConsole.Configuration.IConfigurator
  langs:
  - csharp
  - vb
  name: Run(BuilderBase, GameHost)
  nameWithType: IConfigurator.Run(BuilderBase, GameHost)
  fullName: SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.BuilderBase, SadConsole.GameHost)
  type: Method
  assemblies:
  - SadConsole
  namespace: SadConsole.Configuration
  summary: Called by the <xref href="SadConsole.Configuration.Builder" data-throw-if-not-resolved="false"></xref>; Runs the specific config for this object.
  example: []
  syntax:
    content: void Run(BuilderBase config, GameHost game)
    parameters:
    - id: config
      type: SadConsole.Configuration.BuilderBase
      description: The builder configuration object.
    - id: game
      type: SadConsole.GameHost
      description: The game object being created.
    content.vb: Sub Run(config As BuilderBase, game As GameHost)
  overload: SadConsole.Configuration.IConfigurator.Run*
references:
- uid: SadConsole.Configuration.Builder
  commentId: T:SadConsole.Configuration.Builder
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.Builder.html
  name: Builder
  nameWithType: Builder
  fullName: SadConsole.Configuration.Builder
- uid: SadConsole.Configuration
  commentId: N:SadConsole.Configuration
  isExternal: true
  href: SadConsole.html
  name: SadConsole.Configuration
  nameWithType: SadConsole.Configuration
  fullName: SadConsole.Configuration
  spec.csharp:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
  spec.vb:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
- uid: System.Object.SadConsole.ExtensionsSystem.GetDebuggerDisplayValue
  commentId: M:SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(System.Object)
  parent: SadConsole.ExtensionsSystem
  definition: SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(System.Object)
  href: SadConsole.ExtensionsSystem.html#SadConsole_ExtensionsSystem_GetDebuggerDisplayValue_System_Object_
  name: GetDebuggerDisplayValue(object)
  nameWithType: ExtensionsSystem.GetDebuggerDisplayValue(object)
  fullName: SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(object)
  nameWithType.vb: ExtensionsSystem.GetDebuggerDisplayValue(Object)
  fullName.vb: SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(Object)
  name.vb: GetDebuggerDisplayValue(Object)
  spec.csharp:
  - uid: SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(System.Object)
    name: GetDebuggerDisplayValue
    isExternal: true
    href: SadConsole.ExtensionsSystem.html#SadConsole_ExtensionsSystem_GetDebuggerDisplayValue_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(System.Object)
    name: GetDebuggerDisplayValue
    isExternal: true
    href: SadConsole.ExtensionsSystem.html#SadConsole_ExtensionsSystem_GetDebuggerDisplayValue_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(System.Object)
  commentId: M:SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(System.Object)
  isExternal: true
  href: SadConsole.ExtensionsSystem.html#SadConsole_ExtensionsSystem_GetDebuggerDisplayValue_System_Object_
  name: GetDebuggerDisplayValue(object)
  nameWithType: ExtensionsSystem.GetDebuggerDisplayValue(object)
  fullName: SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(object)
  nameWithType.vb: ExtensionsSystem.GetDebuggerDisplayValue(Object)
  fullName.vb: SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(Object)
  name.vb: GetDebuggerDisplayValue(Object)
  spec.csharp:
  - uid: SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(System.Object)
    name: GetDebuggerDisplayValue
    isExternal: true
    href: SadConsole.ExtensionsSystem.html#SadConsole_ExtensionsSystem_GetDebuggerDisplayValue_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: SadConsole.ExtensionsSystem.GetDebuggerDisplayValue(System.Object)
    name: GetDebuggerDisplayValue
    isExternal: true
    href: SadConsole.ExtensionsSystem.html#SadConsole_ExtensionsSystem_GetDebuggerDisplayValue_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: SadConsole.ExtensionsSystem
  commentId: T:SadConsole.ExtensionsSystem
  parent: SadConsole
  isExternal: true
  href: SadConsole.ExtensionsSystem.html
  name: ExtensionsSystem
  nameWithType: ExtensionsSystem
  fullName: SadConsole.ExtensionsSystem
- uid: SadConsole
  commentId: N:SadConsole
  isExternal: true
  href: SadConsole.html
  name: SadConsole
  nameWithType: SadConsole
  fullName: SadConsole
- uid: SadConsole.Configuration.IConfigurator.Run*
  commentId: Overload:SadConsole.Configuration.IConfigurator.Run
  isExternal: true
  href: SadConsole.Configuration.IConfigurator.html#SadConsole_Configuration_IConfigurator_Run_SadConsole_Configuration_BuilderBase_SadConsole_GameHost_
  name: Run
  nameWithType: IConfigurator.Run
  fullName: SadConsole.Configuration.IConfigurator.Run
- uid: SadConsole.Configuration.BuilderBase
  commentId: T:SadConsole.Configuration.BuilderBase
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.BuilderBase.html
  name: BuilderBase
  nameWithType: BuilderBase
  fullName: SadConsole.Configuration.BuilderBase
- uid: SadConsole.GameHost
  commentId: T:SadConsole.GameHost
  parent: SadConsole
  isExternal: true
  href: SadConsole.GameHost.html
  name: GameHost
  nameWithType: GameHost
  fullName: SadConsole.GameHost
