### YamlMime:ManagedReference
items:
- uid: SadConsole.Configuration.DebugExtensionsImGui
  commentId: T:SadConsole.Configuration.DebugExtensionsImGui
  id: DebugExtensionsImGui
  parent: SadConsole.Configuration
  children:
  - SadConsole.Configuration.DebugExtensionsImGui.EnableImGuiDebugger(SadConsole.Configuration.Builder,SadConsole.Input.Keys,System.Action{System.Boolean},System.Action)
  langs:
  - csharp
  - vb
  name: DebugExtensionsImGui
  nameWithType: DebugExtensionsImGui
  fullName: SadConsole.Configuration.DebugExtensionsImGui
  type: Class
  assemblies:
  - SadConsole.Debug.MonoGame
  namespace: SadConsole.Configuration
  summary: Extensions to enable the ImGui debug UI.
  example: []
  syntax:
    content: public static class DebugExtensionsImGui
    content.vb: Public Module DebugExtensionsImGui
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: SadConsole.Configuration.DebugExtensionsImGui.EnableImGuiDebugger(SadConsole.Configuration.Builder,SadConsole.Input.Keys,System.Action{System.Boolean},System.Action)
  commentId: M:SadConsole.Configuration.DebugExtensionsImGui.EnableImGuiDebugger(SadConsole.Configuration.Builder,SadConsole.Input.Keys,System.Action{System.Boolean},System.Action)
  id: EnableImGuiDebugger(SadConsole.Configuration.Builder,SadConsole.Input.Keys,System.Action{System.Boolean},System.Action)
  isExtensionMethod: true
  parent: SadConsole.Configuration.DebugExtensionsImGui
  langs:
  - csharp
  - vb
  name: EnableImGuiDebugger(Builder, Keys, Action<bool>, Action)
  nameWithType: DebugExtensionsImGui.EnableImGuiDebugger(Builder, Keys, Action<bool>, Action)
  fullName: SadConsole.Configuration.DebugExtensionsImGui.EnableImGuiDebugger(SadConsole.Configuration.Builder, SadConsole.Input.Keys, System.Action<bool>, System.Action)
  type: Method
  assemblies:
  - SadConsole.Debug.MonoGame
  namespace: SadConsole.Configuration
  summary: Adds a <xref href="SadConsole.GameHost.RootComponents" data-throw-if-not-resolved="false"></xref> component that uses the specified hotkey to invoke <xref href="SadConsole.Debug.Debugger.Start" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static Builder EnableImGuiDebugger(this Builder builder, Keys hotkey, Action<bool> openedEventHandler = null, Action closedEventHandler = null)
    parameters:
    - id: builder
      type: SadConsole.Configuration.Builder
      description: The config builder.
    - id: hotkey
      type: SadConsole.Input.Keys
      description: The keyboard key to start the debugger.
    - id: openedEventHandler
      type: System.Action{System.Boolean}
      description: An event handler that's raised when the debugger opens.
    - id: closedEventHandler
      type: System.Action
      description: An event handler that's raised when the debugger closes.
    return:
      type: SadConsole.Configuration.Builder
      description: The config builder.
    content.vb: Public Shared Function EnableImGuiDebugger(builder As Builder, hotkey As Keys, openedEventHandler As Action(Of Boolean) = Nothing, closedEventHandler As Action = Nothing) As Builder
  overload: SadConsole.Configuration.DebugExtensionsImGui.EnableImGuiDebugger*
  nameWithType.vb: DebugExtensionsImGui.EnableImGuiDebugger(Builder, Keys, Action(Of Boolean), Action)
  fullName.vb: SadConsole.Configuration.DebugExtensionsImGui.EnableImGuiDebugger(SadConsole.Configuration.Builder, SadConsole.Input.Keys, System.Action(Of Boolean), System.Action)
  name.vb: EnableImGuiDebugger(Builder, Keys, Action(Of Boolean), Action)
references:
- uid: SadConsole.Configuration
  commentId: N:SadConsole.Configuration
  isExternal: true
  href: SadConsole.html
  name: SadConsole.Configuration
  nameWithType: SadConsole.Configuration
  fullName: SadConsole.Configuration
  spec.csharp:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
  spec.vb:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SadConsole.GameHost.RootComponents
  commentId: P:SadConsole.GameHost.RootComponents
  parent: SadConsole.GameHost
  isExternal: true
  href: SadConsole.GameHost.html#SadConsole_GameHost_RootComponents
  name: RootComponents
  nameWithType: GameHost.RootComponents
  fullName: SadConsole.GameHost.RootComponents
- uid: SadConsole.Debug.Debugger.Start
  commentId: M:SadConsole.Debug.Debugger.Start
  isExternal: true
  href: SadConsole.Debug.Debugger.html#SadConsole_Debug_Debugger_Start
  name: Start()
  nameWithType: Debugger.Start()
  fullName: SadConsole.Debug.Debugger.Start()
  spec.csharp:
  - uid: SadConsole.Debug.Debugger.Start
    name: Start
    isExternal: true
    href: SadConsole.Debug.Debugger.html#SadConsole_Debug_Debugger_Start
  - name: (
  - name: )
  spec.vb:
  - uid: SadConsole.Debug.Debugger.Start
    name: Start
    isExternal: true
    href: SadConsole.Debug.Debugger.html#SadConsole_Debug_Debugger_Start
  - name: (
  - name: )
- uid: SadConsole.Configuration.DebugExtensionsImGui.EnableImGuiDebugger*
  commentId: Overload:SadConsole.Configuration.DebugExtensionsImGui.EnableImGuiDebugger
  isExternal: true
  href: SadConsole.Configuration.DebugExtensionsImGui.html#SadConsole_Configuration_DebugExtensionsImGui_EnableImGuiDebugger_SadConsole_Configuration_Builder_SadConsole_Input_Keys_System_Action_System_Boolean__System_Action_
  name: EnableImGuiDebugger
  nameWithType: DebugExtensionsImGui.EnableImGuiDebugger
  fullName: SadConsole.Configuration.DebugExtensionsImGui.EnableImGuiDebugger
- uid: SadConsole.Configuration.Builder
  commentId: T:SadConsole.Configuration.Builder
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.Builder.html
  name: Builder
  nameWithType: Builder
  fullName: SadConsole.Configuration.Builder
- uid: SadConsole.Input.Keys
  commentId: T:SadConsole.Input.Keys
  parent: SadConsole.Input
  isExternal: true
  href: SadConsole.Input.Keys.html
  name: Keys
  nameWithType: Keys
  fullName: SadConsole.Input.Keys
- uid: System.Action{System.Boolean}
  commentId: T:System.Action{System.Boolean}
  parent: System
  definition: System.Action`1
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<bool>
  nameWithType: Action<bool>
  fullName: System.Action<bool>
  nameWithType.vb: Action(Of Boolean)
  fullName.vb: System.Action(Of Boolean)
  name.vb: Action(Of Boolean)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
- uid: System.Action
  commentId: T:System.Action
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.action
  name: Action
  nameWithType: Action
  fullName: System.Action
- uid: SadConsole.GameHost
  commentId: T:SadConsole.GameHost
  parent: SadConsole
  isExternal: true
  href: SadConsole.GameHost.html
  name: GameHost
  nameWithType: GameHost
  fullName: SadConsole.GameHost
- uid: SadConsole.Input
  commentId: N:SadConsole.Input
  isExternal: true
  href: SadConsole.html
  name: SadConsole.Input
  nameWithType: SadConsole.Input
  fullName: SadConsole.Input
  spec.csharp:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Input
    name: Input
    isExternal: true
    href: SadConsole.Input.html
  spec.vb:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Input
    name: Input
    isExternal: true
    href: SadConsole.Input.html
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: SadConsole
  commentId: N:SadConsole
  isExternal: true
  href: SadConsole.html
  name: SadConsole
  nameWithType: SadConsole
  fullName: SadConsole
