### YamlMime:ManagedReference
items:
- uid: SadConsole.Configuration.StartingScreenConfig
  commentId: T:SadConsole.Configuration.StartingScreenConfig
  id: StartingScreenConfig
  parent: SadConsole.Configuration
  children:
  - SadConsole.Configuration.StartingScreenConfig.#ctor
  - SadConsole.Configuration.StartingScreenConfig.GenerateStartingObject
  - SadConsole.Configuration.StartingScreenConfig.Run(SadConsole.Configuration.Builder,SadConsole.Game)
  langs:
  - csharp
  - vb
  name: StartingScreenConfig
  nameWithType: StartingScreenConfig
  fullName: SadConsole.Configuration.StartingScreenConfig
  type: Class
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole.Configuration
  syntax:
    content: 'public class StartingScreenConfig : IConfigurator'
    content.vb: Public Class StartingScreenConfig Implements IConfigurator
  inheritance:
  - System.Object
  implements:
  - SadConsole.Configuration.IConfigurator
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: SadConsole.Configuration.StartingScreenConfig.Run(SadConsole.Configuration.Builder,SadConsole.Game)
  commentId: M:SadConsole.Configuration.StartingScreenConfig.Run(SadConsole.Configuration.Builder,SadConsole.Game)
  id: Run(SadConsole.Configuration.Builder,SadConsole.Game)
  parent: SadConsole.Configuration.StartingScreenConfig
  langs:
  - csharp
  - vb
  name: Run(Builder, Game)
  nameWithType: StartingScreenConfig.Run(Builder, Game)
  fullName: SadConsole.Configuration.StartingScreenConfig.Run(SadConsole.Configuration.Builder, SadConsole.Game)
  type: Method
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole.Configuration
  summary: Called by the <xref href="SadConsole.Configuration.Builder" data-throw-if-not-resolved="false"></xref>; Runs the specific config for this object.
  example: []
  syntax:
    content: public void Run(Builder configBuilder, Game game)
    parameters:
    - id: configBuilder
      type: SadConsole.Configuration.Builder
    - id: game
      type: SadConsole.Game
      description: The game object being created.
    content.vb: Public Sub Run(configBuilder As Builder, game As Game)
  overload: SadConsole.Configuration.StartingScreenConfig.Run*
  implements:
  - SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.Builder,SadConsole.Game)
- uid: SadConsole.Configuration.StartingScreenConfig.#ctor
  commentId: M:SadConsole.Configuration.StartingScreenConfig.#ctor
  id: '#ctor'
  parent: SadConsole.Configuration.StartingScreenConfig
  langs:
  - csharp
  - vb
  name: StartingScreenConfig()
  nameWithType: StartingScreenConfig.StartingScreenConfig()
  fullName: SadConsole.Configuration.StartingScreenConfig.StartingScreenConfig()
  type: Constructor
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole.Configuration
  syntax:
    content: public StartingScreenConfig()
    content.vb: Public Sub New()
  overload: SadConsole.Configuration.StartingScreenConfig.#ctor*
  nameWithType.vb: StartingScreenConfig.New()
  fullName.vb: SadConsole.Configuration.StartingScreenConfig.New()
  name.vb: New()
- uid: SadConsole.Configuration.StartingScreenConfig.GenerateStartingObject
  commentId: P:SadConsole.Configuration.StartingScreenConfig.GenerateStartingObject
  id: GenerateStartingObject
  parent: SadConsole.Configuration.StartingScreenConfig
  langs:
  - csharp
  - vb
  name: GenerateStartingObject
  nameWithType: StartingScreenConfig.GenerateStartingObject
  fullName: SadConsole.Configuration.StartingScreenConfig.GenerateStartingObject
  type: Property
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole.Configuration
  syntax:
    content: public Func<Game, IScreenObject> GenerateStartingObject { get; set; }
    parameters: []
    return:
      type: System.Func{SadConsole.Game,SadConsole.IScreenObject}
    content.vb: Public Property GenerateStartingObject As Func(Of Game, IScreenObject)
  overload: SadConsole.Configuration.StartingScreenConfig.GenerateStartingObject*
references:
- uid: SadConsole.Configuration
  commentId: N:SadConsole.Configuration
  isExternal: true
  href: SadConsole.html
  name: SadConsole.Configuration
  nameWithType: SadConsole.Configuration
  fullName: SadConsole.Configuration
  spec.csharp:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
  spec.vb:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: SadConsole.Configuration.IConfigurator
  commentId: T:SadConsole.Configuration.IConfigurator
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.IConfigurator.html
  name: IConfigurator
  nameWithType: IConfigurator
  fullName: SadConsole.Configuration.IConfigurator
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SadConsole.Configuration.Builder
  commentId: T:SadConsole.Configuration.Builder
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.Builder.html
  name: Builder
  nameWithType: Builder
  fullName: SadConsole.Configuration.Builder
- uid: SadConsole.Configuration.StartingScreenConfig.Run*
  commentId: Overload:SadConsole.Configuration.StartingScreenConfig.Run
  isExternal: true
  href: SadConsole.Configuration.StartingScreenConfig.html#SadConsole_Configuration_StartingScreenConfig_Run_SadConsole_Configuration_Builder_SadConsole_Game_
  name: Run
  nameWithType: StartingScreenConfig.Run
  fullName: SadConsole.Configuration.StartingScreenConfig.Run
- uid: SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.Builder,SadConsole.Game)
  commentId: M:SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.Builder,SadConsole.Game)
  parent: SadConsole.Configuration.IConfigurator
  isExternal: true
  href: SadConsole.Configuration.IConfigurator.html#SadConsole_Configuration_IConfigurator_Run_SadConsole_Configuration_Builder_SadConsole_Game_
  name: Run(Builder, Game)
  nameWithType: IConfigurator.Run(Builder, Game)
  fullName: SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.Builder, SadConsole.Game)
  spec.csharp:
  - uid: SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.Builder,SadConsole.Game)
    name: Run
    isExternal: true
    href: SadConsole.Configuration.IConfigurator.html#SadConsole_Configuration_IConfigurator_Run_SadConsole_Configuration_Builder_SadConsole_Game_
  - name: (
  - uid: SadConsole.Configuration.Builder
    name: Builder
    isExternal: true
    href: SadConsole.Configuration.Builder.html
  - name: ','
  - name: " "
  - uid: SadConsole.Game
    name: Game
    isExternal: true
    href: SadConsole.Game.html
  - name: )
  spec.vb:
  - uid: SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.Builder,SadConsole.Game)
    name: Run
    isExternal: true
    href: SadConsole.Configuration.IConfigurator.html#SadConsole_Configuration_IConfigurator_Run_SadConsole_Configuration_Builder_SadConsole_Game_
  - name: (
  - uid: SadConsole.Configuration.Builder
    name: Builder
    isExternal: true
    href: SadConsole.Configuration.Builder.html
  - name: ','
  - name: " "
  - uid: SadConsole.Game
    name: Game
    isExternal: true
    href: SadConsole.Game.html
  - name: )
- uid: SadConsole.Game
  commentId: T:SadConsole.Game
  parent: SadConsole
  isExternal: true
  href: SadConsole.Game.html
  name: Game
  nameWithType: Game
  fullName: SadConsole.Game
- uid: SadConsole
  commentId: N:SadConsole
  isExternal: true
  href: SadConsole.html
  name: SadConsole
  nameWithType: SadConsole
  fullName: SadConsole
- uid: SadConsole.Configuration.StartingScreenConfig.#ctor*
  commentId: Overload:SadConsole.Configuration.StartingScreenConfig.#ctor
  isExternal: true
  href: SadConsole.Configuration.StartingScreenConfig.html#SadConsole_Configuration_StartingScreenConfig__ctor
  name: StartingScreenConfig
  nameWithType: StartingScreenConfig.StartingScreenConfig
  fullName: SadConsole.Configuration.StartingScreenConfig.StartingScreenConfig
  nameWithType.vb: StartingScreenConfig.New
  fullName.vb: SadConsole.Configuration.StartingScreenConfig.New
  name.vb: New
- uid: SadConsole.Configuration.StartingScreenConfig.GenerateStartingObject*
  commentId: Overload:SadConsole.Configuration.StartingScreenConfig.GenerateStartingObject
  isExternal: true
  href: SadConsole.Configuration.StartingScreenConfig.html#SadConsole_Configuration_StartingScreenConfig_GenerateStartingObject
  name: GenerateStartingObject
  nameWithType: StartingScreenConfig.GenerateStartingObject
  fullName: SadConsole.Configuration.StartingScreenConfig.GenerateStartingObject
- uid: System.Func{SadConsole.Game,SadConsole.IScreenObject}
  commentId: T:System.Func{SadConsole.Game,SadConsole.IScreenObject}
  parent: System
  definition: System.Func`2
  href: https://learn.microsoft.com/dotnet/api/system.func-2
  name: Func<Game, IScreenObject>
  nameWithType: Func<Game, IScreenObject>
  fullName: System.Func<SadConsole.Game, SadConsole.IScreenObject>
  nameWithType.vb: Func(Of Game, IScreenObject)
  fullName.vb: System.Func(Of SadConsole.Game, SadConsole.IScreenObject)
  name.vb: Func(Of Game, IScreenObject)
  spec.csharp:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: <
  - uid: SadConsole.Game
    name: Game
    isExternal: true
    href: SadConsole.Game.html
  - name: ','
  - name: " "
  - uid: SadConsole.IScreenObject
    name: IScreenObject
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: (
  - name: Of
  - name: " "
  - uid: SadConsole.Game
    name: Game
    isExternal: true
    href: SadConsole.Game.html
  - name: ','
  - name: " "
  - uid: SadConsole.IScreenObject
    name: IScreenObject
    isExternal: true
  - name: )
- uid: System.Func`2
  commentId: T:System.Func`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.func-2
  name: Func<T, TResult>
  nameWithType: Func<T, TResult>
  fullName: System.Func<T, TResult>
  nameWithType.vb: Func(Of T, TResult)
  fullName.vb: System.Func(Of T, TResult)
  name.vb: Func(Of T, TResult)
  spec.csharp:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: <
  - name: T
  - name: ','
  - name: " "
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: ','
  - name: " "
  - name: TResult
  - name: )
