### YamlMime:ManagedReference
items:
- uid: SadConsole.Configuration.DebugExtensionsMouseTint
  commentId: T:SadConsole.Configuration.DebugExtensionsMouseTint
  id: DebugExtensionsMouseTint
  parent: SadConsole.Configuration
  children:
  - SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug(SadConsole.Configuration.Builder)
  - SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug(SadConsole.Configuration.Builder,SadRogue.Primitives.Color)
  langs:
  - csharp
  - vb
  name: DebugExtensionsMouseTint
  nameWithType: DebugExtensionsMouseTint
  fullName: SadConsole.Configuration.DebugExtensionsMouseTint
  type: Class
  assemblies:
  - SadConsole.Extended
  namespace: SadConsole.Configuration
  summary: Extensions class for configuring mouse tint debugging.
  example: []
  syntax:
    content: public static class DebugExtensionsMouseTint
    content.vb: Public Module DebugExtensionsMouseTint
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug(SadConsole.Configuration.Builder)
  commentId: M:SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug(SadConsole.Configuration.Builder)
  id: EnableMouseTintDebug(SadConsole.Configuration.Builder)
  isExtensionMethod: true
  parent: SadConsole.Configuration.DebugExtensionsMouseTint
  langs:
  - csharp
  - vb
  name: EnableMouseTintDebug(Builder)
  nameWithType: DebugExtensionsMouseTint.EnableMouseTintDebug(Builder)
  fullName: SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug(SadConsole.Configuration.Builder)
  type: Method
  assemblies:
  - SadConsole.Extended
  namespace: SadConsole.Configuration
  summary: Adds a <xref href="SadConsole.GameHost.RootComponents" data-throw-if-not-resolved="false"></xref> component that tints the object under the mouse <xref href="SadRogue.Primitives.Color.Purple" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static Builder EnableMouseTintDebug(this Builder builder)
    parameters:
    - id: builder
      type: SadConsole.Configuration.Builder
      description: The config builder.
    return:
      type: SadConsole.Configuration.Builder
      description: The config builder.
    content.vb: Public Shared Function EnableMouseTintDebug(builder As Builder) As Builder
  overload: SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug*
- uid: SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug(SadConsole.Configuration.Builder,SadRogue.Primitives.Color)
  commentId: M:SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug(SadConsole.Configuration.Builder,SadRogue.Primitives.Color)
  id: EnableMouseTintDebug(SadConsole.Configuration.Builder,SadRogue.Primitives.Color)
  isExtensionMethod: true
  parent: SadConsole.Configuration.DebugExtensionsMouseTint
  langs:
  - csharp
  - vb
  name: EnableMouseTintDebug(Builder, Color)
  nameWithType: DebugExtensionsMouseTint.EnableMouseTintDebug(Builder, Color)
  fullName: SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug(SadConsole.Configuration.Builder, SadRogue.Primitives.Color)
  type: Method
  assemblies:
  - SadConsole.Extended
  namespace: SadConsole.Configuration
  summary: Adds a <xref href="SadConsole.GameHost.RootComponents" data-throw-if-not-resolved="false"></xref> component that tints the object under the mouse.
  example: []
  syntax:
    content: public static Builder EnableMouseTintDebug(this Builder builder, Color tintColor)
    parameters:
    - id: builder
      type: SadConsole.Configuration.Builder
      description: The config builder.
    - id: tintColor
      type: SadRogue.Primitives.Color
      description: The color to tint objects.
    return:
      type: SadConsole.Configuration.Builder
      description: The config builder.
    content.vb: Public Shared Function EnableMouseTintDebug(builder As Builder, tintColor As Color) As Builder
  overload: SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug*
references:
- uid: SadConsole.Configuration
  commentId: N:SadConsole.Configuration
  isExternal: true
  href: SadConsole.html
  name: SadConsole.Configuration
  nameWithType: SadConsole.Configuration
  fullName: SadConsole.Configuration
  spec.csharp:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
  spec.vb:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SadConsole.GameHost.RootComponents
  commentId: P:SadConsole.GameHost.RootComponents
  parent: SadConsole.GameHost
  isExternal: true
  href: SadConsole.GameHost.html#SadConsole_GameHost_RootComponents
  name: RootComponents
  nameWithType: GameHost.RootComponents
  fullName: SadConsole.GameHost.RootComponents
- uid: SadRogue.Primitives.Color.Purple
  commentId: F:SadRogue.Primitives.Color.Purple
  isExternal: true
  name: Purple
  nameWithType: Color.Purple
  fullName: SadRogue.Primitives.Color.Purple
- uid: SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug*
  commentId: Overload:SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug
  isExternal: true
  href: SadConsole.Configuration.DebugExtensionsMouseTint.html#SadConsole_Configuration_DebugExtensionsMouseTint_EnableMouseTintDebug_SadConsole_Configuration_Builder_
  name: EnableMouseTintDebug
  nameWithType: DebugExtensionsMouseTint.EnableMouseTintDebug
  fullName: SadConsole.Configuration.DebugExtensionsMouseTint.EnableMouseTintDebug
- uid: SadConsole.Configuration.Builder
  commentId: T:SadConsole.Configuration.Builder
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.Builder.html
  name: Builder
  nameWithType: Builder
  fullName: SadConsole.Configuration.Builder
- uid: SadConsole.GameHost
  commentId: T:SadConsole.GameHost
  parent: SadConsole
  isExternal: true
  href: SadConsole.GameHost.html
  name: GameHost
  nameWithType: GameHost
  fullName: SadConsole.GameHost
- uid: SadConsole
  commentId: N:SadConsole
  isExternal: true
  href: SadConsole.html
  name: SadConsole
  nameWithType: SadConsole
  fullName: SadConsole
- uid: SadRogue.Primitives.Color
  commentId: T:SadRogue.Primitives.Color
  parent: SadRogue.Primitives
  isExternal: true
  name: Color
  nameWithType: Color
  fullName: SadRogue.Primitives.Color
- uid: SadRogue.Primitives
  commentId: N:SadRogue.Primitives
  isExternal: true
  href: SadRogue.html
  name: SadRogue.Primitives
  nameWithType: SadRogue.Primitives
  fullName: SadRogue.Primitives
  spec.csharp:
  - uid: SadRogue
    name: SadRogue
    isExternal: true
    href: SadRogue.html
  - name: .
  - uid: SadRogue.Primitives
    name: Primitives
    isExternal: true
    href: SadRogue.Primitives.html
  spec.vb:
  - uid: SadRogue
    name: SadRogue
    isExternal: true
    href: SadRogue.html
  - name: .
  - uid: SadRogue.Primitives
    name: Primitives
    isExternal: true
    href: SadRogue.Primitives.html
