### YamlMime:ManagedReference
items:
- uid: SadConsole.Configuration.ConfigurationImGui
  commentId: T:SadConsole.Configuration.ConfigurationImGui
  id: ConfigurationImGui
  parent: SadConsole.Configuration
  children:
  - SadConsole.Configuration.ConfigurationImGui.EnableImGui(SadConsole.Configuration.Builder,System.String,System.Single,System.Boolean,System.Action{SadConsole.ImGuiSystem.ImGuiMonoGameComponent})
  langs:
  - csharp
  - vb
  name: ConfigurationImGui
  nameWithType: ConfigurationImGui
  fullName: SadConsole.Configuration.ConfigurationImGui
  type: Class
  assemblies:
  - SadConsole.Debug.MonoGame
  namespace: SadConsole.Configuration
  summary: Extensions to enable ImGui with SadConsole.
  example: []
  syntax:
    content: public static class ConfigurationImGui
    content.vb: Public Module ConfigurationImGui
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: SadConsole.Configuration.ConfigurationImGui.EnableImGui(SadConsole.Configuration.Builder,System.String,System.Single,System.Boolean,System.Action{SadConsole.ImGuiSystem.ImGuiMonoGameComponent})
  commentId: M:SadConsole.Configuration.ConfigurationImGui.EnableImGui(SadConsole.Configuration.Builder,System.String,System.Single,System.Boolean,System.Action{SadConsole.ImGuiSystem.ImGuiMonoGameComponent})
  id: EnableImGui(SadConsole.Configuration.Builder,System.String,System.Single,System.Boolean,System.Action{SadConsole.ImGuiSystem.ImGuiMonoGameComponent})
  isExtensionMethod: true
  parent: SadConsole.Configuration.ConfigurationImGui
  langs:
  - csharp
  - vb
  name: EnableImGui(Builder, string, float, bool, Action<ImGuiMonoGameComponent>)
  nameWithType: ConfigurationImGui.EnableImGui(Builder, string, float, bool, Action<ImGuiMonoGameComponent>)
  fullName: SadConsole.Configuration.ConfigurationImGui.EnableImGui(SadConsole.Configuration.Builder, string, float, bool, System.Action<SadConsole.ImGuiSystem.ImGuiMonoGameComponent>)
  type: Method
  assemblies:
  - SadConsole.Debug.MonoGame
  namespace: SadConsole.Configuration
  summary: Adds the ImGui MonoGame component to MonoGame.
  example: []
  syntax:
    content: public static Builder EnableImGui(this Builder builder, string fontFile = "Roboto-Regular.ttf", float fontSize = 16, bool enableDocking = false, Action<ImGuiMonoGameComponent> startupAction = null)
    parameters:
    - id: builder
      type: SadConsole.Configuration.Builder
      description: The config builder.
    - id: fontFile
      type: System.String
      description: The font file to use with ImGui. Defaults to 'Roboto-Regular.ttf'.
    - id: fontSize
      type: System.Single
      description: The font size to use with ImGui. Defaults to 16.
    - id: enableDocking
      type: System.Boolean
      description: Enables the docking feature of ImGui. Defaults to false.
    - id: startupAction
      type: System.Action{SadConsole.ImGuiSystem.ImGuiMonoGameComponent}
      description: A callback to add objects to the ImGui MonoGame component.
    return:
      type: SadConsole.Configuration.Builder
      description: The config builder.
    content.vb: Public Shared Function EnableImGui(builder As Builder, fontFile As String = "Roboto-Regular.ttf", fontSize As Single = 16, enableDocking As Boolean = False, startupAction As Action(Of ImGuiMonoGameComponent) = Nothing) As Builder
  overload: SadConsole.Configuration.ConfigurationImGui.EnableImGui*
  nameWithType.vb: ConfigurationImGui.EnableImGui(Builder, String, Single, Boolean, Action(Of ImGuiMonoGameComponent))
  fullName.vb: SadConsole.Configuration.ConfigurationImGui.EnableImGui(SadConsole.Configuration.Builder, String, Single, Boolean, System.Action(Of SadConsole.ImGuiSystem.ImGuiMonoGameComponent))
  name.vb: EnableImGui(Builder, String, Single, Boolean, Action(Of ImGuiMonoGameComponent))
references:
- uid: SadConsole.Configuration
  commentId: N:SadConsole.Configuration
  isExternal: true
  href: SadConsole.html
  name: SadConsole.Configuration
  nameWithType: SadConsole.Configuration
  fullName: SadConsole.Configuration
  spec.csharp:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
  spec.vb:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SadConsole.Configuration.ConfigurationImGui.EnableImGui*
  commentId: Overload:SadConsole.Configuration.ConfigurationImGui.EnableImGui
  isExternal: true
  href: SadConsole.Configuration.ConfigurationImGui.html#SadConsole_Configuration_ConfigurationImGui_EnableImGui_SadConsole_Configuration_Builder_System_String_System_Single_System_Boolean_System_Action_SadConsole_ImGuiSystem_ImGuiMonoGameComponent__
  name: EnableImGui
  nameWithType: ConfigurationImGui.EnableImGui
  fullName: SadConsole.Configuration.ConfigurationImGui.EnableImGui
- uid: SadConsole.Configuration.Builder
  commentId: T:SadConsole.Configuration.Builder
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.Builder.html
  name: Builder
  nameWithType: Builder
  fullName: SadConsole.Configuration.Builder
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.Action{SadConsole.ImGuiSystem.ImGuiMonoGameComponent}
  commentId: T:System.Action{SadConsole.ImGuiSystem.ImGuiMonoGameComponent}
  parent: System
  definition: System.Action`1
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<ImGuiMonoGameComponent>
  nameWithType: Action<ImGuiMonoGameComponent>
  fullName: System.Action<SadConsole.ImGuiSystem.ImGuiMonoGameComponent>
  nameWithType.vb: Action(Of ImGuiMonoGameComponent)
  fullName.vb: System.Action(Of SadConsole.ImGuiSystem.ImGuiMonoGameComponent)
  name.vb: Action(Of ImGuiMonoGameComponent)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: SadConsole.ImGuiSystem.ImGuiMonoGameComponent
    name: ImGuiMonoGameComponent
    isExternal: true
    href: SadConsole.ImGuiSystem.ImGuiMonoGameComponent.html
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: SadConsole.ImGuiSystem.ImGuiMonoGameComponent
    name: ImGuiMonoGameComponent
    isExternal: true
    href: SadConsole.ImGuiSystem.ImGuiMonoGameComponent.html
  - name: )
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
