### YamlMime:ManagedReference
items:
- uid: SadConsole.Configuration
  commentId: N:SadConsole.Configuration
  id: SadConsole.Configuration
  children:
  - SadConsole.Configuration.Builder
  - SadConsole.Configuration.BuilderBase
  - SadConsole.Configuration.CallbackConfig
  - SadConsole.Configuration.ConfigurationImGui
  - SadConsole.Configuration.ConfigureWindowConfig
  - SadConsole.Configuration.DebugExtensionsFocusedTint
  - SadConsole.Configuration.DebugExtensionsImGui
  - SadConsole.Configuration.DebugExtensionsMouseTint
  - SadConsole.Configuration.Extensions
  - SadConsole.Configuration.ExtensionsHost
  - SadConsole.Configuration.FontConfig
  - SadConsole.Configuration.FpsConfig
  - SadConsole.Configuration.IConfigurator
  - SadConsole.Configuration.MonoGameCallbackConfig
  - SadConsole.Configuration.MonoGameSettings
  - SadConsole.Configuration.SplashScreenConfig
  - SadConsole.Configuration.StartingConsoleConfig
  - SadConsole.Configuration.StartingScreenConfig
  langs:
  - csharp
  - vb
  name: SadConsole.Configuration
  nameWithType: SadConsole.Configuration
  fullName: SadConsole.Configuration
  type: Namespace
  assemblies:
  - SadConsole.Debug.MonoGame
references:
- uid: SadConsole.Configuration.DebugExtensionsImGui
  commentId: T:SadConsole.Configuration.DebugExtensionsImGui
  isExternal: true
  href: SadConsole.Configuration.DebugExtensionsImGui.html
  name: DebugExtensionsImGui
  nameWithType: DebugExtensionsImGui
  fullName: SadConsole.Configuration.DebugExtensionsImGui
- uid: SadConsole.Configuration.ConfigurationImGui
  commentId: T:SadConsole.Configuration.ConfigurationImGui
  isExternal: true
  href: SadConsole.Configuration.ConfigurationImGui.html
  name: ConfigurationImGui
  nameWithType: ConfigurationImGui
  fullName: SadConsole.Configuration.ConfigurationImGui
- uid: SadConsole.Configuration.Builder
  commentId: T:SadConsole.Configuration.Builder
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.Builder.html
  name: Builder
  nameWithType: Builder
  fullName: SadConsole.Configuration.Builder
- uid: SadConsole.Configuration.BuilderBase
  commentId: T:SadConsole.Configuration.BuilderBase
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.BuilderBase.html
  name: BuilderBase
  nameWithType: BuilderBase
  fullName: SadConsole.Configuration.BuilderBase
- uid: SadConsole.Configuration.Extensions
  commentId: T:SadConsole.Configuration.Extensions
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.Extensions.html
  name: Extensions
  nameWithType: Extensions
  fullName: SadConsole.Configuration.Extensions
- uid: SadConsole.Configuration.CallbackConfig
  commentId: T:SadConsole.Configuration.CallbackConfig
  isExternal: true
  href: SadConsole.Configuration.CallbackConfig.html
  name: CallbackConfig
  nameWithType: CallbackConfig
  fullName: SadConsole.Configuration.CallbackConfig
- uid: SadConsole.Configuration.ConfigureWindowConfig
  commentId: T:SadConsole.Configuration.ConfigureWindowConfig
  isExternal: true
  href: SadConsole.Configuration.ConfigureWindowConfig.html
  name: ConfigureWindowConfig
  nameWithType: ConfigureWindowConfig
  fullName: SadConsole.Configuration.ConfigureWindowConfig
- uid: SadConsole.Configuration.StartingConsoleConfig
  commentId: T:SadConsole.Configuration.StartingConsoleConfig
  isExternal: true
  href: SadConsole.Configuration.StartingConsoleConfig.html
  name: StartingConsoleConfig
  nameWithType: StartingConsoleConfig
  fullName: SadConsole.Configuration.StartingConsoleConfig
- uid: SadConsole.Configuration.FontConfig
  commentId: T:SadConsole.Configuration.FontConfig
  isExternal: true
  href: SadConsole.Configuration.FontConfig.html
  name: FontConfig
  nameWithType: FontConfig
  fullName: SadConsole.Configuration.FontConfig
- uid: SadConsole.Configuration.IConfigurator
  commentId: T:SadConsole.Configuration.IConfigurator
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.IConfigurator.html
  name: IConfigurator
  nameWithType: IConfigurator
  fullName: SadConsole.Configuration.IConfigurator
- uid: SadConsole.Configuration.SplashScreenConfig
  commentId: T:SadConsole.Configuration.SplashScreenConfig
  isExternal: true
  href: SadConsole.Configuration.SplashScreenConfig.html
  name: SplashScreenConfig
  nameWithType: SplashScreenConfig
  fullName: SadConsole.Configuration.SplashScreenConfig
- uid: SadConsole.Configuration.StartingScreenConfig
  commentId: T:SadConsole.Configuration.StartingScreenConfig
  isExternal: true
  href: SadConsole.Configuration.StartingScreenConfig.html
  name: StartingScreenConfig
  nameWithType: StartingScreenConfig
  fullName: SadConsole.Configuration.StartingScreenConfig
- uid: SadConsole.Configuration.DebugExtensionsFocusedTint
  commentId: T:SadConsole.Configuration.DebugExtensionsFocusedTint
  isExternal: true
  href: SadConsole.Configuration.DebugExtensionsFocusedTint.html
  name: DebugExtensionsFocusedTint
  nameWithType: DebugExtensionsFocusedTint
  fullName: SadConsole.Configuration.DebugExtensionsFocusedTint
- uid: SadConsole.Configuration.DebugExtensionsMouseTint
  commentId: T:SadConsole.Configuration.DebugExtensionsMouseTint
  isExternal: true
  href: SadConsole.Configuration.DebugExtensionsMouseTint.html
  name: DebugExtensionsMouseTint
  nameWithType: DebugExtensionsMouseTint
  fullName: SadConsole.Configuration.DebugExtensionsMouseTint
- uid: SadConsole.Configuration.ExtensionsHost
  commentId: T:SadConsole.Configuration.ExtensionsHost
  isExternal: true
  href: SadConsole.Configuration.ExtensionsHost.html
  name: ExtensionsHost
  nameWithType: ExtensionsHost
  fullName: SadConsole.Configuration.ExtensionsHost
- uid: SadConsole.Configuration.FpsConfig
  commentId: T:SadConsole.Configuration.FpsConfig
  isExternal: true
  href: SadConsole.Configuration.FpsConfig.html
  name: FpsConfig
  nameWithType: FpsConfig
  fullName: SadConsole.Configuration.FpsConfig
- uid: SadConsole.Configuration.MonoGameSettings
  commentId: T:SadConsole.Configuration.MonoGameSettings
  isExternal: true
  href: SadConsole.Configuration.MonoGameSettings.html
  name: MonoGameSettings
  nameWithType: MonoGameSettings
  fullName: SadConsole.Configuration.MonoGameSettings
- uid: SadConsole.Configuration.MonoGameCallbackConfig
  commentId: T:SadConsole.Configuration.MonoGameCallbackConfig
  isExternal: true
  href: SadConsole.Configuration.MonoGameCallbackConfig.html
  name: MonoGameCallbackConfig
  nameWithType: MonoGameCallbackConfig
  fullName: SadConsole.Configuration.MonoGameCallbackConfig
- uid: SadConsole.Configuration
  commentId: N:SadConsole.Configuration
  isExternal: true
  href: SadConsole.html
  name: SadConsole.Configuration
  nameWithType: SadConsole.Configuration
  fullName: SadConsole.Configuration
  spec.csharp:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
  spec.vb:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
