### YamlMime:ManagedReference
items:
- uid: SadConsole.Configuration.IConfigurator
  commentId: T:SadConsole.Configuration.IConfigurator
  id: IConfigurator
  parent: SadConsole.Configuration
  children:
  - SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.Builder,SadConsole.Game)
  langs:
  - csharp
  - vb
  name: IConfigurator
  nameWithType: IConfigurator
  fullName: SadConsole.Configuration.IConfigurator
  type: Interface
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole.Configuration
  summary: Configuration interface that's added to the <xref href="SadConsole.Configuration.Builder" data-throw-if-not-resolved="false"></xref> object.
  example: []
  syntax:
    content: public interface IConfigurator
    content.vb: Public Interface IConfigurator
- uid: SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.Builder,SadConsole.Game)
  commentId: M:SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.Builder,SadConsole.Game)
  id: Run(SadConsole.Configuration.Builder,SadConsole.Game)
  parent: SadConsole.Configuration.IConfigurator
  langs:
  - csharp
  - vb
  name: Run(Builder, Game)
  nameWithType: IConfigurator.Run(Builder, Game)
  fullName: SadConsole.Configuration.IConfigurator.Run(SadConsole.Configuration.Builder, SadConsole.Game)
  type: Method
  assemblies:
  - SadConsole.Host.MonoGame
  namespace: SadConsole.Configuration
  summary: Called by the <xref href="SadConsole.Configuration.Builder" data-throw-if-not-resolved="false"></xref>; Runs the specific config for this object.
  example: []
  syntax:
    content: void Run(Builder config, Game game)
    parameters:
    - id: config
      type: SadConsole.Configuration.Builder
      description: The builder configuration object.
    - id: game
      type: SadConsole.Game
      description: The game object being created.
    content.vb: Sub Run(config As Builder, game As Game)
  overload: SadConsole.Configuration.IConfigurator.Run*
references:
- uid: SadConsole.Configuration.Builder
  commentId: T:SadConsole.Configuration.Builder
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.Builder.html
  name: Builder
  nameWithType: Builder
  fullName: SadConsole.Configuration.Builder
- uid: SadConsole.Configuration
  commentId: N:SadConsole.Configuration
  isExternal: true
  href: SadConsole.html
  name: SadConsole.Configuration
  nameWithType: SadConsole.Configuration
  fullName: SadConsole.Configuration
  spec.csharp:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
  spec.vb:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
- uid: SadConsole.Configuration.IConfigurator.Run*
  commentId: Overload:SadConsole.Configuration.IConfigurator.Run
  isExternal: true
  href: SadConsole.Configuration.IConfigurator.html#SadConsole_Configuration_IConfigurator_Run_SadConsole_Configuration_Builder_SadConsole_Game_
  name: Run
  nameWithType: IConfigurator.Run
  fullName: SadConsole.Configuration.IConfigurator.Run
- uid: SadConsole.Game
  commentId: T:SadConsole.Game
  parent: SadConsole
  isExternal: true
  href: SadConsole.Game.html
  name: Game
  nameWithType: Game
  fullName: SadConsole.Game
- uid: SadConsole
  commentId: N:SadConsole
  isExternal: true
  href: SadConsole.html
  name: SadConsole
  nameWithType: SadConsole
  fullName: SadConsole
