### YamlMime:ManagedReference
items:
- uid: SadConsole.Configuration
  commentId: N:SadConsole.Configuration
  id: SadConsole.Configuration
  children:
  - SadConsole.Configuration.Builder
  - SadConsole.Configuration.CallbackConfig
  - SadConsole.Configuration.Extensions
  - SadConsole.Configuration.ExtensionsHost
  - SadConsole.Configuration.FontConfig
  - SadConsole.Configuration.FpsConfig
  - SadConsole.Configuration.IConfigurator
  - SadConsole.Configuration.InternalHostStartupData
  - SadConsole.Configuration.InternalStartupData
  - SadConsole.Configuration.MonoGameCallbackConfig
  - SadConsole.Configuration.SplashScreenConfig
  - SadConsole.Configuration.StartingConsoleConfig
  - SadConsole.Configuration.StartingScreenConfig
  langs:
  - csharp
  - vb
  name: SadConsole.Configuration
  nameWithType: SadConsole.Configuration
  fullName: SadConsole.Configuration
  type: Namespace
  assemblies:
  - SadConsole
references:
- uid: SadConsole.Configuration.Builder
  commentId: T:SadConsole.Configuration.Builder
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.Builder.html
  name: Builder
  nameWithType: Builder
  fullName: SadConsole.Configuration.Builder
- uid: SadConsole.Configuration.Extensions
  commentId: T:SadConsole.Configuration.Extensions
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.Extensions.html
  name: Extensions
  nameWithType: Extensions
  fullName: SadConsole.Configuration.Extensions
- uid: SadConsole.Configuration.CallbackConfig
  commentId: T:SadConsole.Configuration.CallbackConfig
  isExternal: true
  href: SadConsole.Configuration.CallbackConfig.html
  name: CallbackConfig
  nameWithType: CallbackConfig
  fullName: SadConsole.Configuration.CallbackConfig
- uid: SadConsole.Configuration.StartingConsoleConfig
  commentId: T:SadConsole.Configuration.StartingConsoleConfig
  isExternal: true
  href: SadConsole.Configuration.StartingConsoleConfig.html
  name: StartingConsoleConfig
  nameWithType: StartingConsoleConfig
  fullName: SadConsole.Configuration.StartingConsoleConfig
- uid: SadConsole.Configuration.FontConfig
  commentId: T:SadConsole.Configuration.FontConfig
  isExternal: true
  href: SadConsole.Configuration.FontConfig.html
  name: FontConfig
  nameWithType: FontConfig
  fullName: SadConsole.Configuration.FontConfig
- uid: SadConsole.Configuration.IConfigurator
  commentId: T:SadConsole.Configuration.IConfigurator
  parent: SadConsole.Configuration
  isExternal: true
  href: SadConsole.Configuration.IConfigurator.html
  name: IConfigurator
  nameWithType: IConfigurator
  fullName: SadConsole.Configuration.IConfigurator
- uid: SadConsole.Configuration.InternalStartupData
  commentId: T:SadConsole.Configuration.InternalStartupData
  isExternal: true
  href: SadConsole.Configuration.InternalStartupData.html
  name: InternalStartupData
  nameWithType: InternalStartupData
  fullName: SadConsole.Configuration.InternalStartupData
- uid: SadConsole.Configuration.SplashScreenConfig
  commentId: T:SadConsole.Configuration.SplashScreenConfig
  isExternal: true
  href: SadConsole.Configuration.SplashScreenConfig.html
  name: SplashScreenConfig
  nameWithType: SplashScreenConfig
  fullName: SadConsole.Configuration.SplashScreenConfig
- uid: SadConsole.Configuration.StartingScreenConfig
  commentId: T:SadConsole.Configuration.StartingScreenConfig
  isExternal: true
  href: SadConsole.Configuration.StartingScreenConfig.html
  name: StartingScreenConfig
  nameWithType: StartingScreenConfig
  fullName: SadConsole.Configuration.StartingScreenConfig
- uid: SadConsole.Configuration.ExtensionsHost
  commentId: T:SadConsole.Configuration.ExtensionsHost
  isExternal: true
  href: SadConsole.Configuration.ExtensionsHost.html
  name: ExtensionsHost
  nameWithType: ExtensionsHost
  fullName: SadConsole.Configuration.ExtensionsHost
- uid: SadConsole.Configuration.FpsConfig
  commentId: T:SadConsole.Configuration.FpsConfig
  isExternal: true
  href: SadConsole.Configuration.FpsConfig.html
  name: FpsConfig
  nameWithType: FpsConfig
  fullName: SadConsole.Configuration.FpsConfig
- uid: SadConsole.Configuration.InternalHostStartupData
  commentId: T:SadConsole.Configuration.InternalHostStartupData
  isExternal: true
  href: SadConsole.Configuration.InternalHostStartupData.html
  name: InternalHostStartupData
  nameWithType: InternalHostStartupData
  fullName: SadConsole.Configuration.InternalHostStartupData
- uid: SadConsole.Configuration.MonoGameCallbackConfig
  commentId: T:SadConsole.Configuration.MonoGameCallbackConfig
  isExternal: true
  href: SadConsole.Configuration.MonoGameCallbackConfig.html
  name: MonoGameCallbackConfig
  nameWithType: MonoGameCallbackConfig
  fullName: SadConsole.Configuration.MonoGameCallbackConfig
- uid: SadConsole.Configuration
  commentId: N:SadConsole.Configuration
  isExternal: true
  href: SadConsole.html
  name: SadConsole.Configuration
  nameWithType: SadConsole.Configuration
  fullName: SadConsole.Configuration
  spec.csharp:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
  spec.vb:
  - uid: SadConsole
    name: SadConsole
    isExternal: true
    href: SadConsole.html
  - name: .
  - uid: SadConsole.Configuration
    name: Configuration
    isExternal: true
    href: SadConsole.Configuration.html
